### ISSUE TITLE
Promise.all() Could Leave Cancel Message Sending Without Warning

### ISSUE THREAD

**Issue by chriswsh** [codefortulsa/courtbot-engine#6]
#6 The Promise.all() calls inside module.exports.sendDueReminders() and module.exports.checkMissingCases() would cancel message sending without warning if one of the promises in the array fails before all the others complete.

**Comment by pipakin** [comment]
👍 Agreed.

**Comment by chriswsh** [comment]
Update: I was wrong. My mistake :-S

I just tested a similarly structured promise chain (Chrome, Edge, Firefox), and all the promises sent to the Promise.all() do run to completion. If there's an early failure, Promise.all().catch() might run before the other promises complete.

I did notice another behavior I didn't expect. If a promise chain sent to Promise.all() has an ending catch() statement, Promise.all().catch() is not called, no matter how many promises are rejected.

var valueArray = [1,2,3];
Promise.all(valueArray.map((a) => {
&nbsp;&nbsp;&nbsp;&nbsp;return new Promise((resolve, reject) => {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var waitTime = (Math.random() * 1000 + 500) >> 0;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(() => {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reject(a);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.log(`Promise with ${a} completed`);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}, waitTime);
&nbsp;&nbsp;&nbsp;&nbsp;}).then(() => {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// no-op
&nbsp;&nbsp;&nbsp;&nbsp;}).catch((value) => {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.warn(`Promise with ${value} rejected`);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return `strike ${value}`;
&nbsp;&nbsp;&nbsp;&nbsp;});
})).then((value) => {
&nbsp;&nbsp;&nbsp;&nbsp;// I run, and the return value from Promise.all is the array of values returned by the catch() statement
&nbsp;&nbsp;&nbsp;&nbsp;console.log(`Promise.all() successfully completed! Value: ${value}`);
}).catch((err) => {
&nbsp;&nbsp;&nbsp;&nbsp;// I don't run, even though all promises were rejected
&nbsp;&nbsp;&nbsp;&nbsp;console.error(`Promise.all() rejected at value ${err}`);
});

Console Output, Depending on Wait Time:
Promise with 1 completed
Promise with 1 rejected
Promise with 3 completed
Promise with 3 rejected
Promise with 2 completed
Promise with 2 rejected
Promise.all() successfully completed! Value: strike 1, strike 2, strike 3

If you leave the catch() statement out of the inner promise, you get instead, depending on wait time:

Promise with 2 completed
Promise.all() rejected at value 2
Promise with 1 completed
Promise with 3 completed

If this is how you want the code to behave, it looks like Promise.all() is the way to go.

**Comment by pipakin** [comment]
This has been handled and is now closed.
